
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chire
 */
public class frmPrincipalTP2 extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipalTP2
     */
    public frmPrincipalTP2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTP2 = new javax.swing.JLabel();
        lblEX1 = new javax.swing.JLabel();
        lblNBeleves = new javax.swing.JLabel();
        txtNBeleves = new javax.swing.JTextField();
        sldNBeleves = new javax.swing.JSlider();
        btnPrixvoyage = new javax.swing.JButton();
        txtPrixvoyage = new javax.swing.JTextField();
        lbmEX2 = new javax.swing.JLabel();
        lblVal1 = new javax.swing.JLabel();
        lblVAL2 = new javax.swing.JLabel();
        txtVAL1 = new javax.swing.JTextField();
        txtVAL2 = new javax.swing.JTextField();
        btnEchanger = new javax.swing.JButton();
        lblEX3 = new javax.swing.JLabel();
        lblSaisirNBetoiles = new javax.swing.JLabel();
        txtNBetoiles = new javax.swing.JTextField();
        btnDessinerTriangle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTirageAlatoire = new javax.swing.JButton();
        lblNBcoups = new javax.swing.JLabel();
        txtNBcoups = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTriangle = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNombres = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTP2.setText("TP2 ");

        lblEX1.setText("EX 1 ");

        lblNBeleves.setText("Nombres d'élèves");

        sldNBeleves.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldNBelevesStateChanged(evt);
            }
        });

        btnPrixvoyage.setText("prix du voyage ");
        btnPrixvoyage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrixvoyageMouseClicked(evt);
            }
        });

        lbmEX2.setText("EX 2 ");

        lblVal1.setText("valeur 1");

        lblVAL2.setText("valeur 2");

        btnEchanger.setText("échanger");
        btnEchanger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEchangerMouseClicked(evt);
            }
        });

        lblEX3.setText("EX 3");

        lblSaisirNBetoiles.setText("sasir un nombre d'étoiles");

        btnDessinerTriangle.setText("dessiner triangle");
        btnDessinerTriangle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDessinerTriangleMouseClicked(evt);
            }
        });

        jLabel1.setText("EX 4");

        btnTirageAlatoire.setText("tirage aléatoire");
        btnTirageAlatoire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTirageAlatoireMouseClicked(evt);
            }
        });

        lblNBcoups.setText("nombre de coups");

        txtTriangle.setColumns(20);
        txtTriangle.setRows(5);
        jScrollPane1.setViewportView(txtTriangle);

        txtNombres.setColumns(20);
        txtNombres.setRows(5);
        jScrollPane2.setViewportView(txtNombres);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSaisirNBetoiles)
                        .addGap(18, 18, 18)
                        .addComponent(txtNBetoiles, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDessinerTriangle, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btnTirageAlatoire)
                        .addContainerGap(92, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNBcoups)
                                .addGap(18, 18, 18)
                                .addComponent(txtNBcoups, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(sldNBeleves, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(150, 150, 150)
                                    .addComponent(lblTP2))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lblEX1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNBeleves)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNBeleves, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(16, 16, 16)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrixvoyage, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrixvoyage, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEX3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(176, 176, 176))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbmEX2)
                                    .addGap(99, 99, 99))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVAL2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVAL2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblVal1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVAL1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(74, 74, 74))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnEchanger, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTP2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblEX1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lbmEX2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNBeleves)
                            .addComponent(txtNBeleves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldNBeleves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrixvoyage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrixvoyage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVal1)
                            .addComponent(txtVAL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVAL2)
                            .addComponent(txtVAL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEchanger)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEX3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaisirNBetoiles)
                    .addComponent(txtNBetoiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDessinerTriangle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTirageAlatoire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNBcoups)
                            .addComponent(txtNBcoups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // EX 1
    private void btnPrixvoyageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrixvoyageMouseClicked
        // TODO add your handling code here:
        double prix;
            double heberg;
            double total;
            if(sldNBeleves.getValue() <= 25)
            {
                prix = 67.30;
            }
            else
            {
                 prix = 61;
            }
            if(sldNBeleves.getValue() <= 30)
            {
                heberg = 4.75;
            }
            else
            {
                if(sldNBeleves.getValue() > 35)
                {
                    heberg = 3.5;
                }
                else
                {
                    heberg = 4;   
                }
            }
            // Total = prix voyage + nourriture + hébergement
            total = (prix *sldNBeleves.getValue()) + (3.5 * sldNBeleves.getValue()) + (heberg * sldNBeleves.getValue());
            txtPrixvoyage.setText(String.valueOf(total));
    
    }//GEN-LAST:event_btnPrixvoyageMouseClicked

    private void sldNBelevesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldNBelevesStateChanged
        // TODO add your handling code here:
        txtNBeleves.setText(String.valueOf(sldNBeleves.getValue()));
    }//GEN-LAST:event_sldNBelevesStateChanged

// EX 2 
    private void btnEchangerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEchangerMouseClicked
        // TODO add your handling code here:
        if (txtVAL1.getText().compareTo("")==0)
        {
            JOptionPane.showMessageDialog(this,"Saisir une valeur 1");
        }
            else 
        {
             if(txtVAL2.getText().compareTo("")==0)
            {
                JOptionPane.showMessageDialog(this, "Saisir une valeur 2");
            }
            else
            {
                String temp = txtVAL2.getText();
                txtVAL2.setText(txtVAL1.getText());
                txtVAL1.setText(temp);
            }
        }
            
    }//GEN-LAST:event_btnEchangerMouseClicked
 //EX 3
    private void btnDessinerTriangleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDessinerTriangleMouseClicked
        // TODO add your handling code here:
        if(txtNBetoiles.getText().compareTo("")==0)
        {
            JOptionPane.showMessageDialog(this, "Saisir un nombre d'étoiles");
        }
        else
        {
            txtTriangle.setText("");
            for(int i = 1 ; i <= Integer.parseInt(txtNBetoiles.getText()) ; i++)
            {
                String ligne = "";
                for(int j = 1 ; j <= i  ; j++)
                {
                    
                    ligne = ligne + " * ";
                   
                }
                txtTriangle.setText(txtTriangle.getText() + ligne + "\n");
            }
        }
        
    }//GEN-LAST:event_btnDessinerTriangleMouseClicked
// EX 4
    private void btnTirageAlatoireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTirageAlatoireMouseClicked
        // TODO add your handling code here:
         Random r = new Random();
        int nb1 = r.nextInt(21) + 1;
        int nb2 = r.nextInt(21) + 1;
        int nbCoups = 1;
        txtNombres.setText("");
        while( nb1 != nb2)
        {
            txtNombres.setText(txtNombres.getText() + "\n" + " nb1 = " + nb1 + "   nb2 = " + nb2 + "\n");
            nb1 = r.nextInt(21) + 1;
            nb2 = r.nextInt(21) + 1;
            nbCoups++;
            // Demo
        }
        txtNombres.setText(txtNombres.getText() + "\n" + " nb1 = " + nb1 + "   nb2 = " + nb2 + "\n");
        txtNBcoups.setText(String.valueOf(nbCoups));
                                      
    }//GEN-LAST:event_btnTirageAlatoireMouseClicked
        
    
    

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalTP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalTP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalTP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalTP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipalTP2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDessinerTriangle;
    private javax.swing.JButton btnEchanger;
    private javax.swing.JButton btnPrixvoyage;
    private javax.swing.JButton btnTirageAlatoire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEX1;
    private javax.swing.JLabel lblEX3;
    private javax.swing.JLabel lblNBcoups;
    private javax.swing.JLabel lblNBeleves;
    private javax.swing.JLabel lblSaisirNBetoiles;
    private javax.swing.JLabel lblTP2;
    private javax.swing.JLabel lblVAL2;
    private javax.swing.JLabel lblVal1;
    private javax.swing.JLabel lbmEX2;
    private javax.swing.JSlider sldNBeleves;
    private javax.swing.JTextField txtNBcoups;
    private javax.swing.JTextField txtNBeleves;
    private javax.swing.JTextField txtNBetoiles;
    private javax.swing.JTextArea txtNombres;
    private javax.swing.JTextField txtPrixvoyage;
    private javax.swing.JTextArea txtTriangle;
    private javax.swing.JTextField txtVAL1;
    private javax.swing.JTextField txtVAL2;
    // End of variables declaration//GEN-END:variables
}
